### ISSUE TITLE
Lineup kept reordering during the game

### ISSUE THREAD

**Issue by JeffreyFalgout** [thbrown/softball-scorer#6]
![](https://user-images.githubusercontent.com/2907401/63823896-8fc29880-c912-11e9-8d9e-5f0297cbcb74.png)

I kept having to manually fix it so that Sara G was before Paul.

If I go into the game config, the lineup type is `Normal`, not `No Consecutive Females`: 
![](https://user-images.githubusercontent.com/2907401/63823965-c13b6400-c912-11e9-95b8-8b1d7ab01404.png)

**Comment by thbrown** [comment]
Fixed in 79ac244df02c7b8e26f7ac0fc5686c526293dd54

Deployed earlier this week.
